@hostname = localhost
@port = 3001
@personId = 9
@missingPersonId = 5
@host = http://{{hostname}}:{{port}}

###

DELETE {{host}}/api/customers/{{personId}} HTTP/1.1
Accept: application/json

###

DELETE {{host}}/api/customers/{{missingPersonId}} HTTP/1.1
Accept: application/json