@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

@customerId = 9
@customerEmail = test1@email
@missingCustomerId = 5

### GET ALL

GET {{host}}/api/customers HTTP/1.1
Accept: application/json

### GET ONE

GET {{host}}/api/customers/{{customerId}} HTTP/1.1
Accept: application/json

###

GET {{host}}/api/customers/{{missingCustomerId}} HTTP/1.1
Accept: application/json

### GET BY EMAIL

GET {{host}}/api/customers/email/{{customerEmail}} HTTP/1.1
Accept: application/json

### POST

POST {{host}}/api/customers HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "John Do email",
  "companyName": "myCompany",
  "firstname": "john",
  "lastname": "do"
}

###

POST {{host}}/api/customers HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "test1@email",
  "companyName": "myCompany",
  "firstname": "test1",
  "lastname": "test1"
}

### DELETE

DELETE {{host}}/api/customers/{{customerId}} HTTP/1.1
Accept: application/json

###

DELETE {{host}}/api/customers/{{missingCustomerId}} HTTP/1.1
Accept: application/json