@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

@customerId =22
@customerEmail = test1@email
@missingCustomerId = 23

###
### GET ALL
###

GET {{host}}/api/customers HTTP/1.1
Accept: application/json

###
### GET ONE
###

GET {{host}}/api/customers/{{customerId}} HTTP/1.1
Accept: application/json

###

GET {{host}}/api/customers/{{missingCustomerId}} HTTP/1.1
Accept: application/json

###
### GET ONE BY EMAIL
###

GET {{host}}/api/customers/email/{{customerEmail}} HTTP/1.1
Accept: application/json

###
### POST ONE
###

POST {{host}}/api/customers HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "JohnDo@email",
  "companyName": "myCompany",
  "firstname": "john",
  "lastname": "do",
  "password":"password"
}

###

POST {{host}}/api/customers HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "test1@email",
  "companyName": "myCompany",
  "firstname": "test1",
  "lastname": "test1",
  "password":"password"
}

###
### DELETE ONE
###

DELETE {{host}}/api/customers/{{customerId}} HTTP/1.1
Accept: application/json

###

DELETE {{host}}/api/customers/{{missingCustomerId}} HTTP/1.1
Accept: application/json