@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

@objectId = 9
@missingObjectId = 5

###
### GET ALL
###

GET {{host}}/api/orders HTTP/1.1
Accept: application/json

###
### GET ONE
###

GET {{host}}/api/orders/{{objectId}} HTTP/1.1
Accept: application/json

###

GET {{host}}/api/orders/{{missingObjectId}} HTTP/1.1
Accept: application/json

###
### POST
###

POST {{host}}/api/orders HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "John Do email",
  "companyName": "myCompany",
  "firstname": "john",
  "lastname": "do"
}

###

POST {{host}}/api/orders HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "test1@email",
  "companyName": "myCompany",
  "firstname": "test1",
  "lastname": "test1"
}

###
### DELETE
###

DELETE {{host}}/api/orders/{{objectId}} HTTP/1.1
Accept: application/json

###

DELETE {{host}}/api/orders/{{missingObjectId}} HTTP/1.1
Accept: application/json