@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

@objectId = 2
@missingObjectId = 5

###
### GET ALL
###

GET {{host}}/api/products HTTP/1.1
Accept: application/json

###
### GET ONE
###

GET {{host}}/api/products/{{objectId}} HTTP/1.1
Accept: application/json

###

GET {{host}}/api/products/{{missingObjectId}} HTTP/1.1
Accept: application/json

###
### POST ONE
###

POST {{host}}/api/products HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "productName": "Ballon de basket",
  "unitPrice": 1,
  "description": "On utilise ses mains et on le met dans le panier"
}

###

POST {{host}}/api/products HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "productName": "Chaussures de sport",
  "unitPrice": 3,
  "description": "vous savez, ces truc qu'on porte au pieds ..."
}

###
### DELETE ONE
###

DELETE {{host}}/api/products/{{objectId}} HTTP/1.1
Accept: application/json

###

DELETE {{host}}/api/products/{{missingObjectId}} HTTP/1.1
Accept: application/json